Validation of missing private key, some DRYing
[#171666374]

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -7,13 +7,19 @@ cwd="$(cd "$(dirname "$0")" && pwd)"
 source "$cwd/common"
 
 payload="$(cat /dev/stdin)"
-
 uri="$(get source uri <<< "$payload")"
-private_key="$(get source private_key <<< "$payload")"
 branch="$(get source branch <<< "$payload")"
+private_key="$(get source private_key <<< "$payload")"
 kustomization_yaml_path="$(get source kustomization_yaml_path <<< "$payload")"
-[ "$kustomization_yaml_path" == null ] \
+[ -z "$kustomization_yaml_path" ] \
     && kustomization_yaml_path=k8s/base/kustomization.yaml
+
+if [ -z "$private_key" ]
+then
+    echo "Missing private key!"
+    exit 1
+fi
+
 input_tag="$(get version tag <<< "$payload")"
 
 clone "$uri" /tmp/repo "$branch" "$private_key"
diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -11,12 +11,19 @@ export GIT_COMMITTER_EMAIL=engineering@boclips.com
 
 payload="$(cat /dev/stdin)"
 uri="$(get source uri <<< "$payload")"
+branch="$(get source branch <<< "$payload")"
 private_key="$(get source private_key <<< "$payload")"
 kustomization_yaml_path="$(get source kustomization_yaml_path <<< "$payload")"
-[ "$kustomization_yaml_path" == null ] \
+[ -z "$kustomization_yaml_path" ] \
     && kustomization_yaml_path=k8s/base/kustomization.yaml
 
-clone "$uri" /tmp/repo master "$private_key"
+if [ -z "$private_key" ]
+then
+    echo "Missing private key!"
+    exit 1
+fi
+
+clone "$uri" /tmp/repo "$branch" "$private_key"
 
 cd /tmp/repo
 
diff --git a/test/common b/test/common
--- a/test/common
+++ b/test/common
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
+cwd="$(cd "$(dirname "$0")" && pwd)"
+
 create () {
-    image_id="$(docker build --quiet "$1")"
+    image_id="$(cat "$cwd/../test_image_id")"
     docker create \
         --interactive \
         --entrypoint="$2" \
@@ -44,6 +46,23 @@ assert_equal_json () {
         echo
         echo "Actual output:"
         echo "$comparable_actual_output"
+        echo
+        exit 1
+    fi
+}
+
+assert_equal () {
+    if [ "$1" == "$2" ]
+    then
+        echo "Test passed"
+    else
+        echo "Test failed"
+        echo
+        echo "Expected output:"
+        echo "$1"
+        echo
+        echo "Actual output:"
+        echo "$2"
         echo
         exit 1
     fi
