Cope with reuse of container in 'check'
[#171666374]

diff --git a/test/common b/test/common
--- a/test/common
+++ b/test/common
@@ -1,14 +1,33 @@
 #!/usr/bin/env bash
 
-run () {
-    (
+create () {
     image_id="$(docker build --quiet "$1")"
-    docker run \
+    docker create \
         --interactive \
         --entrypoint="$2" \
-        "$image_id" \
-        <<< "$3"
-    )
+        "$image_id"
+}
+
+run () {
+    container_id="$(create "$1" "$2")"
+    docker start --interactive "$container_id" <<< "$3"
+}
+
+assert_runs_twice () {
+    container_id="$(create "$1" "$2")"
+    echo "Run 1"
+    echo
+    docker start --interactive "$container_id" <<< "$3"
+    echo
+    echo "Run 2"
+    echo
+    if docker start --interactive "$container_id" <<< "$3"
+    then
+        echo "Test passed"
+    else
+        echo "Test failed"
+        exit 1
+    fi
 }
 
 assert_equal_json () {
