Implement out
[#171666374]

diff --git a/test/out b/test/out
--- a/test/out
+++ b/test/out
@@ -2,3 +2,109 @@
 
 set -e
 
+cwd="$(cd "$(dirname "$0")" && pwd)"
+# shellcheck disable=SC1090
+source "$cwd/common"
+
+uri="/tmp/remote-repo"
+
+input="$(
+jq \
+    --null-input \
+    --arg uri "$uri" \
+    --arg branch master \
+    --arg private_key "unused-in-this-test" \
+    '{
+       source: {
+         uri: $uri,
+         branch: $branch,
+         private_key: $private_key,
+         kustomization_yaml_path: "some-k8s/kustomization.yaml"
+       },
+       params: {}
+     }'
+)"
+
+expected_output="$(cat <<EOF
+{
+  "version": "124",
+  "metadata": [
+    {
+      "name": "tag",
+      "value": "124"
+    }
+  ]
+}
+EOF
+)"
+
+image_id="$(docker build --quiet "$cwd/..")"
+docker_output="$(
+# shellcheck disable=SC1004
+docker run \
+    --interactive \
+    --entrypoint=bash \
+    "$image_id" \
+    -c \
+    '
+input="$(cat /dev/stdin)"
+mkdir /tmp/remote-repo
+(
+cd "/tmp/remote-repo"
+git init --bare --quiet
+)
+git clone /tmp/remote-repo local-repo
+(
+cd local-repo
+mkdir some-k8s
+cat <<EOF > some-k8s/kustomization.yaml
+before:
+newTag: "123"
+after:
+EOF
+git add .
+git config --global user.email "engineering@boclips.com"
+git config --global user.name "A previous CI run"
+git commit --quiet --message=LOL
+git push
+)
+
+output="$(/opt/resource/out <<< "$input")"
+
+git -C local-repo pull --quiet
+
+jq --null-input \
+    --raw-output \
+    --arg newyaml "$(cat local-repo/some-k8s/kustomization.yaml)" \
+    --arg output "$output" \
+    '\''
+{
+  newyaml: $newyaml,
+  output: $output
+}
+'\''
+' <<< "$input"
+)"
+
+new_yaml="$(jq --raw-output .newyaml <<< "$docker_output")"
+actual_output="$(jq --raw-output .output <<< "$docker_output")"
+
+echo "out bumps emitted version"
+assert_equal_json \
+    "$expected_output" \
+    "$actual_output"
+
+echo "out pushes bumped version"
+
+if echo "$new_yaml" | grep -q 'newTag: "124"' \
+    && echo "$new_yaml" | grep -q 'boclips-version: "124"'
+then
+    echo "Test passed"
+else
+    echo "Test failed"
+    echo
+    echo "Expected to find the 124 tag in:"
+    echo "$new_yaml"
+    echo
+    exit 1
+fi
