Temporarily cat the misbehaving private key
Need to debug CI, and can't execute this outside of the pipeline. I
promise to rotate it. It's read-only anyway.

[#171666374]

diff --git a/resource/common b/resource/common
--- a/resource/common
+++ b/resource/common
@@ -46,7 +46,12 @@ clone () {
         wrapped_git -C "$destination" pull --quiet
     else
         log "Cloning the repo"
-        wrapped_git clone --quiet "$uri" "$destination"
+        if ! wrapped_git clone --quiet "$uri" "$destination"
+        then
+            log "Couldn't clone"
+            cat "$private_key_path"
+            exit 1
+        fi
     fi
 }
 
